name: variance

packages:
  - packages/**
  - apps/**

command:
  version:
    branch: main
    releaseUrl: true

scripts:
  format:
    run: melos exec dart . --fix
    description: Run `dart format` for all packages.